// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativegameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_BASICATTACK);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_COMBO01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_COMBO02);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_COMBO03);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_COMBO04);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_END);

//(Extern) is decleartion only
extern int TestTest = 0;


/**
 * 
 */
class CAbilitySystemNativeTags
{
public:
	CAbilitySystemNativeTags();
	~CAbilitySystemNativeTags();
};
